server:
  port: 9003

spring:
  application:
    name: REGISTRATION-SERVICE
  h2:
    console:
      enabled: true

#Eureka-client-config  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
  
#Logging COnfiguration
logging:
  level:
    org.springframework: DEBUG
    com.codebuffer.departmnent: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: department.log